### ISSUE TITLE
Incomplete StatusSummary

### ISSUE THREAD

**Issue by joehumphries** [statusio/statusio-go#2]
Hi, again,..

Not sure if by design, but the StatusSummary doesn't contain all the expected information.

The direct StatusSummary gives:

- status_overall
- Status
- incidents 
- maintenance

However the struct (status_types.go) just handles Status under results?

Thanks

**Comment by joet3ch** [comment]
Hi Joe,

I'm sorry for the troubles!

The StatusSummary structure is now updated to handle all of the returned data.

Due to the issues that you discovered, we're going to be reviewing the entire statusio-go library in the very near future. Please let us know if you come across anything else.

Thanks for your help,
-joe

**Comment by joehumphries** [comment]
No worries.. :)

I think there are a few bits and bobs.  But it is going in the right direction.
